use_frameworks!

target 'SWApplicationEnvironment_Example' do
  pod 'SWApplicationEnvironment', :path => '../'

  target 'SWApplicationEnvironment_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
